# Generated by Django 2.2 on 2023-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
